{
 "title": "FastFood Delivery - Overview",
 "tags": [
  "fastfood",
  "delivery"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Avg HTTP Duration (ms) by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (job) (rate(http_request_duration_ms_sum[1m]))) / (sum by (job) (rate(http_request_duration_ms_count[1m])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP Request Rate (req/s) by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_request_duration_ms_count[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Process CPU (user+system) by Service (cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job) (rate(process_cpu_user_seconds_total[1m]) + rate(process_cpu_system_seconds_total[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Resident Memory by Service (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job) (process_resident_memory_bytes)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}