{
 "title": "Order Service - Logs",
 "refresh": "5s",
 "panels": [
  {
   "title": "Order Service Logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 12 },
   "targets": [
    {
     "expr": "{container=\"order-service\"}"
    }
   ]
  },
  {
   "title": "Error Log Count (5m window)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"order-service\"} |= \" 5\" [5m]))"
    }
   ]
  },
  {
   "title": "Error Rate (per minute)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 12, "w": 12, "h": 4 },
   "targets": [
    {
     "expr": "sum(rate({container=\"order-service\"} |= \" 5\" [1m]))"
    }
   ]
  }
 ]
}